import type {
  CashFlowReportResponse,
  CommissionReportResponse,
  Invoice,
  LedgerEntry,
  Payout,
  PayoutSchedule,
  ReconciliationRecord,
  RevenueReportResponse,
  TaxReportResponse,
} from "./types";

const now = new Date();
const day = 24 * 60 * 60 * 1000;

function isoDaysAgo(days: number): string {
  return new Date(now.getTime() - days * day).toISOString();
}

export const MOCK_LEDGER_ENTRIES: LedgerEntry[] = [
  {
    ledger_id: 1101,
    booking_id: 5001,
    host_id: 301,
    user_id: 901,
    transaction_type: "GUEST_PAYMENT",
    entry_type: "CREDIT",
    amount: 12500,
    balance_after: 12500,
    reference_id: "TXN-1101",
    description: "Guest booking payment received",
    status: "COMPLETED",
    created_at: isoDaysAgo(1),
    updated_at: isoDaysAgo(1),
    host_name: "Aman Verma",
    user_name: "Rahul Mehta",
    property_name: "Skyline Residency",
  },
  {
    ledger_id: 1102,
    booking_id: 5001,
    host_id: 301,
    user_id: 901,
    transaction_type: "PLATFORM_COMMISSION",
    entry_type: "DEBIT",
    amount: 1875,
    balance_after: 10625,
    reference_id: "TXN-1102",
    description: "Platform commission deduction",
    status: "COMPLETED",
    created_at: isoDaysAgo(1),
    updated_at: isoDaysAgo(1),
    host_name: "Aman Verma",
    user_name: "Rahul Mehta",
    property_name: "Skyline Residency",
  },
  {
    ledger_id: 1103,
    booking_id: 5002,
    host_id: 302,
    user_id: 902,
    transaction_type: "HOST_EARNING",
    entry_type: "CREDIT",
    amount: 9800,
    balance_after: 20425,
    reference_id: "TXN-1103",
    description: "Host earning credited",
    status: "COMPLETED",
    created_at: isoDaysAgo(2),
    updated_at: isoDaysAgo(2),
    host_name: "Priya Nair",
    user_name: "Sonia Kapoor",
    property_name: "Palm Grove Suites",
  },
  {
    ledger_id: 1104,
    booking_id: 5003,
    host_id: 303,
    user_id: 903,
    transaction_type: "PAYOUT",
    entry_type: "DEBIT",
    amount: 15000,
    balance_after: 5425,
    reference_id: "TXN-1104",
    description: "Weekly payout initiated",
    status: "PENDING",
    created_at: isoDaysAgo(3),
    updated_at: isoDaysAgo(3),
    host_name: "Rohit Sinha",
    user_name: "Ananya Roy",
    property_name: "Blue Haven Retreat",
  },
  {
    ledger_id: 1105,
    booking_id: 5004,
    host_id: 304,
    user_id: 904,
    transaction_type: "REFUND",
    entry_type: "DEBIT",
    amount: 3200,
    balance_after: 2225,
    reference_id: "TXN-1105",
    description: "Partial guest refund",
    status: "COMPLETED",
    created_at: isoDaysAgo(4),
    updated_at: isoDaysAgo(4),
    host_name: "Nikita Sharma",
    user_name: "Vikas Jain",
    property_name: "Urban Nest",
  },
];

export const MOCK_HOST_LEDGER = {
  rows: MOCK_LEDGER_ENTRIES.filter((x) => x.host_id === 301),
  balance: 85420,
};

export const MOCK_GUEST_LEDGER = {
  rows: MOCK_LEDGER_ENTRIES.filter((x) => x.user_id === 901),
  totalSpent: 28600,
};

export const MOCK_PAYOUTS: Payout[] = [
  {
    payout_id: 7001,
    host_id: 301,
    host_name: "Aman Verma",
    amount: 24500,
    status: "QUEUED",
    payout_method: "BANK_TRANSFER",
    reference_id: "PAY-7001",
    initiated_by: "SYSTEM",
    initiated_at: isoDaysAgo(1),
    completed_at: null,
    failure_reason: null,
    period_start: isoDaysAgo(8),
    period_end: isoDaysAgo(1),
    tds_rate: 1,
    tds_amount: 245,
    net_amount: 24255,
  },
  {
    payout_id: 7002,
    host_id: 302,
    host_name: "Priya Nair",
    amount: 18200,
    status: "PROCESSING",
    payout_method: "UPI",
    reference_id: "PAY-7002",
    initiated_by: "ADMIN",
    initiated_at: isoDaysAgo(2),
    completed_at: null,
    failure_reason: null,
    period_start: isoDaysAgo(10),
    period_end: isoDaysAgo(3),
    tds_rate: 1,
    tds_amount: 182,
    net_amount: 18018,
  },
  {
    payout_id: 7003,
    host_id: 303,
    host_name: "Rohit Sinha",
    amount: 21400,
    status: "COMPLETED",
    payout_method: "BANK_TRANSFER",
    reference_id: "PAY-7003",
    initiated_by: "SYSTEM",
    initiated_at: isoDaysAgo(4),
    completed_at: isoDaysAgo(3),
    failure_reason: null,
    period_start: isoDaysAgo(14),
    period_end: isoDaysAgo(7),
    tds_rate: 1,
    tds_amount: 214,
    net_amount: 21186,
  },
  {
    payout_id: 7004,
    host_id: 304,
    host_name: "Nikita Sharma",
    amount: 6800,
    status: "FAILED",
    payout_method: "UPI",
    reference_id: "PAY-7004",
    initiated_by: "ADMIN",
    initiated_at: isoDaysAgo(5),
    completed_at: null,
    failure_reason: "UPI handle not active",
    period_start: isoDaysAgo(15),
    period_end: isoDaysAgo(8),
    tds_rate: 0,
    tds_amount: 0,
    net_amount: 6800,
  },
];

export const MOCK_SCHEDULES: PayoutSchedule[] = [
  {
    schedule_id: 8101,
    host_id: 301,
    host_name: "Aman Verma",
    frequency: "WEEKLY",
    next_payout_date: isoDaysAgo(-2),
    last_payout_date: isoDaysAgo(5),
    min_payout_amount: 1000,
    is_active: true,
    payout_method: "BANK_TRANSFER",
    created_at: isoDaysAgo(40),
  },
  {
    schedule_id: 8102,
    host_id: 302,
    host_name: "Priya Nair",
    frequency: "BIWEEKLY",
    next_payout_date: isoDaysAgo(-4),
    last_payout_date: isoDaysAgo(10),
    min_payout_amount: 1500,
    is_active: true,
    payout_method: "UPI",
    created_at: isoDaysAgo(45),
  },
  {
    schedule_id: 8103,
    host_id: 304,
    host_name: "Nikita Sharma",
    frequency: "MONTHLY",
    next_payout_date: isoDaysAgo(-8),
    last_payout_date: isoDaysAgo(20),
    min_payout_amount: 2500,
    is_active: false,
    payout_method: "BANK_TRANSFER",
    created_at: isoDaysAgo(60),
  },
];

export const MOCK_RECON_RECORDS: ReconciliationRecord[] = [
  {
    recon_id: 9101,
    booking_id: 5001,
    payment_amount: 12500,
    expected_amount: 12500,
    payout_amount: 9800,
    variance: 0,
    status: "MATCHED",
    resolved_by: null,
    resolved_at: null,
    notes: null,
    created_at: isoDaysAgo(1),
    host_name: "Aman Verma",
    user_name: "Rahul Mehta",
    property_name: "Skyline Residency",
  },
  {
    recon_id: 9102,
    booking_id: 5002,
    payment_amount: 10900,
    expected_amount: 11200,
    payout_amount: 8600,
    variance: -300,
    status: "VARIANCE",
    resolved_by: null,
    resolved_at: null,
    notes: "Gateway fee mismatch",
    created_at: isoDaysAgo(2),
    host_name: "Priya Nair",
    user_name: "Sonia Kapoor",
    property_name: "Palm Grove Suites",
  },
  {
    recon_id: 9103,
    booking_id: 5003,
    payment_amount: 7600,
    expected_amount: 7600,
    payout_amount: 0,
    variance: 7600,
    status: "PENDING",
    resolved_by: null,
    resolved_at: null,
    notes: null,
    created_at: isoDaysAgo(3),
    host_name: "Rohit Sinha",
    user_name: "Ananya Roy",
    property_name: "Blue Haven Retreat",
  },
  {
    recon_id: 9104,
    booking_id: 5004,
    payment_amount: 4300,
    expected_amount: 4300,
    payout_amount: 3200,
    variance: 0,
    status: "RESOLVED",
    resolved_by: 1,
    resolved_at: isoDaysAgo(1),
    notes: "Adjusted by admin",
    created_at: isoDaysAgo(6),
    host_name: "Nikita Sharma",
    user_name: "Vikas Jain",
    property_name: "Urban Nest",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    invoice_id: 9901,
    invoice_number: "AAJAO/2526/INV/000901",
    booking_id: 5001,
    host_id: 301,
    user_id: 901,
    invoice_type: "BOOKING_RECEIPT",
    subtotal: 10593,
    tax_amount: 1907,
    tax_rate: 18,
    total: 12500,
    hsn_sac_code: "996311",
    gstin: "27ABCDE1234F1Z5",
    pdf_url: null,
    status: "GENERATED",
    created_at: isoDaysAgo(1),
    cgst: 953.5,
    sgst: 953.5,
    igst: 0,
    is_inter_state: false,
    place_of_supply: "Maharashtra",
    supplier_gstin: "27AAJOO1234F1Z9",
    tds_rate: 1,
    tds_amount: 125,
    host_name: "Aman Verma",
    user_name: "Rahul Mehta",
    property_name: "Skyline Residency",
  },
  {
    invoice_id: 9902,
    invoice_number: "AAJAO/2526/INV/000902",
    booking_id: 5002,
    host_id: 302,
    user_id: 902,
    invoice_type: "HOST_COMMISSION",
    subtotal: 8475,
    tax_amount: 1525,
    tax_rate: 18,
    total: 10000,
    hsn_sac_code: "998599",
    gstin: "29ABCDE1234F1Z9",
    pdf_url: null,
    status: "SENT",
    created_at: isoDaysAgo(2),
    cgst: 0,
    sgst: 0,
    igst: 1525,
    is_inter_state: true,
    place_of_supply: "Karnataka",
    supplier_gstin: "27AAJOO1234F1Z9",
    tds_rate: 1,
    tds_amount: 100,
    host_name: "Priya Nair",
    user_name: "Sonia Kapoor",
    property_name: "Palm Grove Suites",
  },
  {
    invoice_id: 9903,
    invoice_number: "AAJAO/2526/INV/000903",
    booking_id: 5003,
    host_id: 303,
    user_id: 903,
    invoice_type: "PAYOUT_STATEMENT",
    subtotal: 6780,
    tax_amount: 1220,
    tax_rate: 18,
    total: 8000,
    hsn_sac_code: "996311",
    gstin: "07ABCDE1234F1Z1",
    pdf_url: null,
    status: "VOID",
    created_at: isoDaysAgo(4),
    cgst: 610,
    sgst: 610,
    igst: 0,
    is_inter_state: false,
    place_of_supply: "Delhi",
    supplier_gstin: "27AAJOO1234F1Z9",
    tds_rate: 0,
    tds_amount: 0,
    host_name: "Rohit Sinha",
    user_name: "Ananya Roy",
    property_name: "Blue Haven Retreat",
  },
];

export const MOCK_REVENUE_REPORT: RevenueReportResponse = {
  data: [
    { period: "Oct 2025", revenue: 170000, bookings: 96, avgValue: 1771 },
    { period: "Nov 2025", revenue: 185000, bookings: 102, avgValue: 1814 },
    { period: "Dec 2025", revenue: 210000, bookings: 111, avgValue: 1892 },
    { period: "Jan 2026", revenue: 198000, bookings: 103, avgValue: 1922 },
    { period: "Feb 2026", revenue: 232000, bookings: 118, avgValue: 1966 },
    { period: "Mar 2026", revenue: 255000, bookings: 126, avgValue: 2024 },
  ],
  totals: { revenue: 1250000, bookings: 656, avgValue: 1905 },
};

export const MOCK_COMMISSION_REPORT: CommissionReportResponse = {
  data: [
    { period: "Oct 2025", commission: 25500, rate: 15, transactions: 96 },
    { period: "Nov 2025", commission: 27750, rate: 15, transactions: 102 },
    { period: "Dec 2025", commission: 31500, rate: 15, transactions: 111 },
    { period: "Jan 2026", commission: 29700, rate: 15, transactions: 103 },
    { period: "Feb 2026", commission: 34800, rate: 15, transactions: 118 },
    { period: "Mar 2026", commission: 38250, rate: 15, transactions: 126 },
  ],
  totals: { totalCommission: 187500, avgRate: 15, transactions: 656 },
};

export const MOCK_TAX_REPORT: TaxReportResponse = {
  data: [
    { period: "Oct 2025", gstCollected: 30600, gstPayable: 27800, tdsDeducted: 2200, cgstCollected: 15300, sgstCollected: 15300, igstCollected: 0 },
    { period: "Nov 2025", gstCollected: 33300, gstPayable: 30100, tdsDeducted: 2400, cgstCollected: 16650, sgstCollected: 16650, igstCollected: 0 },
    { period: "Dec 2025", gstCollected: 37800, gstPayable: 34200, tdsDeducted: 2800, cgstCollected: 18900, sgstCollected: 18900, igstCollected: 0 },
    { period: "Jan 2026", gstCollected: 35640, gstPayable: 32100, tdsDeducted: 2600, cgstCollected: 17820, sgstCollected: 17820, igstCollected: 0 },
    { period: "Feb 2026", gstCollected: 41760, gstPayable: 37600, tdsDeducted: 3000, cgstCollected: 20880, sgstCollected: 20880, igstCollected: 0 },
    { period: "Mar 2026", gstCollected: 45900, gstPayable: 41200, tdsDeducted: 3200, cgstCollected: 22950, sgstCollected: 22950, igstCollected: 0 },
  ],
  totals: {
    gstCollected: 225000,
    gstPayable: 203000,
    tdsDeducted: 16200,
    cgstCollected: 112500,
    sgstCollected: 112500,
    igstCollected: 0,
  },
};

export const MOCK_CASHFLOW_REPORT: CashFlowReportResponse = {
  data: [
    { period: "Oct 2025", inflow: 170000, outflow: 132000, netFlow: 38000 },
    { period: "Nov 2025", inflow: 185000, outflow: 146000, netFlow: 39000 },
    { period: "Dec 2025", inflow: 210000, outflow: 167500, netFlow: 42500 },
    { period: "Jan 2026", inflow: 198000, outflow: 158000, netFlow: 40000 },
    { period: "Feb 2026", inflow: 232000, outflow: 184500, netFlow: 47500 },
    { period: "Mar 2026", inflow: 255000, outflow: 202000, netFlow: 53000 },
  ],
  totals: {
    totalInflow: 1250000,
    totalOutflow: 990000,
    netFlow: 260000,
  },
};
