// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17o7FiMRGHkiY9Lcbj6InLpz5_d2FNeE',
    appId: '1:1006999733744:web:04989e5d227b13c7050935',
    messagingSenderId: '1006999733744',
    projectId: 'aajoo-bdb20',
    authDomain: 'aajoo-bdb20.firebaseapp.com',
    storageBucket: 'aajoo-bdb20.firebasestorage.app',
    measurementId: 'G-RZM3YM0EKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2kVt5P61l6E0KvnUGjP1vy2gviCk-WI',
    appId: '1:1006999733744:android:f7bc7af82334be5a050935',
    messagingSenderId: '1006999733744',
    projectId: 'aajoo-bdb20',
    storageBucket: 'aajoo-bdb20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsII1fZ0d2bDTX7d4HuRMeksL73CyEYI',
    appId: '1:1006999733744:ios:d18b876d15ef8a2b050935',
    messagingSenderId: '1006999733744',
    projectId: 'aajoo-bdb20',
    storageBucket: 'aajoo-bdb20.firebasestorage.app',
    iosBundleId: 'com.aajoo.aajoohomes',
  );

}