const DATA = [
  { t:"Access & staff", d:"Who can get into the panel at all, and what they may do once inside.", items:[
    ["Admin login","Sign in at /admin/login.","/admin/login","","Lands on the dashboard."],
    ["Wrong password","Try a wrong password.","/admin/login","","Refused plainly. No database text, no hint about which field was wrong."],
    ["Session survives reload","Refresh a deep admin page.","/admin/verify-token","","Stays signed in; no bounce to login."],
    ["Guest token is useless","Sign in as a guest, then open /admin/dashboard.","","","Refused. A renter token must never open the panel."],
    ["Staff list","Open staff members.","/admin/members/list","","All admins with roles and status."],
    ["Create an admin","Add a new staff member.","/admin/create","","Only a super admin may. Created and can sign in."],
    ["Change a role","Change someone's role.","/admin/members/role","","Their permissions change on their next load."],
    ["Suspend a member","Set a member inactive.","/admin/members/status","","They can no longer sign in."],
    ["Roles list","Open roles.","/admin/roles/list","","Roles and their permissions render."],
    ["Logout","Sign out, then press Back.","/admin/logout","","No admin data renders from cache."],
  ]},
  { t:"Dashboard & analytics", d:"The numbers leadership will quote. Check they reconcile, not just that they render.", items:[
    ["Dashboard","Open the dashboard.","/admin/dashboard","","Every tile has a real number — no zeros standing in for missing data."],
    ["Analytics summary","Open Analytics.","/admin/analytics/summary","","Totals match the bookings and users lists."],
    ["Graphs","Change the date range.","/admin/analytics/graph","","Chart redraws for the range chosen."],
    ["Locations","Open location analytics.","/admin/analytics/locations","","Cities ranked sensibly."],
    ["Booking analytics","Open Booking Analytics.","/admin/bookings/analytics","","Trends and totals agree with the bookings list."],
    ["Geo bookings","Open Geo Bookings.","","","Map plots bookings in the right places."],
    ["Property analytics","Open Property Analytics, then one property.","/admin/properties/analytic/search","/admin/property/analytic/detail","Views and conversion per listing."],
    ["Reports","Open Reports.","","","Generates without error; export downloads."],
  ]},
  { t:"Users", d:"Guest accounts and their identity records.", items:[
    ["User list","Open Users; search and page through.","/admin/user/search","","Search finds by name, email and phone."],
    ["User detail","Open one user.","/admin/user/single","","Profile, bookings and verification state."],
    ["Create a user","Add a user manually.","/admin/user/create","","Aadhaar field accepts digits only. Account is created."],
    ["Suspend a user","Set a user inactive.","/admin/user/update/status","","They can no longer sign in."],
    ["Verification queue","Open the verification list.","/admin/user/verification","","Pending identity checks listed."],
    ["Approve identity","Manually verify a user.","/admin/user/verify","","Marked verified; the change shows on their account."],
    ["Delete a user","Delete a throwaway account.","/admin/user/delete","","Confirms first; bookings history survives."],
  ]},
  { t:"Hosts & KYC", d:"The people taking money. This is where verification decisions are made.", items:[
    ["Host list","Open Hosts.","/admin/host/search","","All hosts with property counts and status."],
    ["Host detail","Open one host.","/admin/host/detail/:hostId","","Properties, bookings, payouts and KYC state."],
    ["KYC detail","Open a host's identity check.","/admin/host/kyc/detail/:hostId","","Documents and the decision evidence are visible."],
    ["Approve KYC","Approve a pending host.","/admin/host/kyc/approve","","Marked verified; any held listings go live by themselves."],
    ["Reject KYC","Reject one.","/admin/host/kyc/reject","","Reason captured; host is told; listings stay off."],
    ["Host performance","Open a host's performance.","/admin/host/performance/summary","","Ratings and conversion look plausible."],
    ["Hold a payout","Place a payout on hold.","/admin/host/payout/hold","","Held and visible as held."],
    ["Release a payout","Release it.","/admin/host/payout/release","","Returns to the queue."],
    ["Assign a property","Assign a listing to a host.","/admin/host/search/assign-property","","Moves to that host's portal."],
  ]},
  { t:"Properties & listing queue", d:"The catalogue, and approving what goes into it.", items:[
    ["Property list","Open Properties; search and sort.","/admin/properties/search","","29,000+ listings page and search without hanging."],
    ["Property detail","Review one listing.","/admin/properties/load","","Everything the host entered."],
    ["Add a property","Add one for a host.","/listing/submit","","Five-step wizard; admin is never asked to verify their own identity."],
    ["Edit a property","Press Edit on a listing.","/listing/draft/:propertyId","","Opens the SAME five-step wizard, all fields and photos restored."],
    ["Take a listing off","Toggle a listing inactive.","/admin/properties/update-status","","Disappears from public search."],
    ["Verify a listing","Approve a submitted listing.","/admin/properties/verify","","Marked verified; visible to guests."],
    ["Listing queue","Open Listing Verification.","/admin/listing/queue","/admin/listing/detail/:propertyId","Submitted listings awaiting review."],
    ["Review a listing","Approve or reject from the queue.","/admin/listing/review","","Decision sticks; host is told."],
    ["Nearby distances","Set airport and station distances.","/admin/property/nearby","/admin/property/nearby/save","Appear on the public property page."],
    ["Delete an image","Remove one photo.","/admin/properties/delete/image","","Gone from the gallery; others unaffected."],
    ["Delete a property","Delete a test listing.","/admin/property/delete","","Confirms first; removed from search."],
  ]},
  { t:"Bookings", d:"Every stay on the platform, and intervening when something goes wrong.", items:[
    ["Booking list","Open Bookings; filter by status.","/admin/booking/search","","Guest names populate — not blank."],
    ["Booking detail","Open one.","/admin/booking/detail","","Guest, host, property, money, history."],
    ["Staying guest","Open a booking made for someone else.","/admin/guest-profiles/for-booking/:bookingId","","Traveller shown; their ID opens."],
    ["Change status","Move a booking's status.","/admin/booking/status/update","/admin/booking/status/list","Both sides are notified."],
    ["Edit a booking","Amend a booking.","/admin/booking/update","","Saves and the change is auditable."],
  ]},
  { t:"Negotiations & disputes", d:"Oversight of the product's core mechanic, and cleaning up after it.", items:[
    ["Negotiations list","Open Negotiations.","/admin/negotiations/list","","Every offer with its state and property."],
    ["Message thread","Open the thread behind an offer.","/admin/negotiations/messages","","What was actually said."],
    ["Disputes","Open Disputes.","/admin/disputes/list","","KYC flags and payout variances listed."],
    ["Resolve a dispute","Resolve one.","/admin/disputes/resolve","","Closed with a reason; disappears from the open list."],
  ]},
  { t:"Finance", d:"Real money. Check arithmetic against source records, not just that pages load.", items:[
    ["Finance dashboard","Open Financial Overview.","/admin/finance/dashboard","","Revenue, commission and payable reconcile."],
    ["Ledger","Open Ledgers; search.","/admin/finance/ledger/search","/admin/finance/ledger/:ledgerId","Entries balance; each traces to a booking."],
    ["Host ledger","Open one host's ledger.","/admin/finance/ledger/host/:hostId","","Matches what that host sees in their portal."],
    ["Export ledger","Export it.","/admin/finance/ledger/export","","File downloads and opens with the same figures."],
    ["Invoices","Open Invoices; open one.","/admin/finance/invoice/search","/admin/finance/invoice/:invoiceId","GST correct; totals match the booking."],
    ["Download invoice","Download the PDF.","/admin/finance/invoice/:invoiceId/download","","Opens; figures match the screen."],
    ["Void an invoice","Void a test invoice.","/admin/finance/invoice/void/:invoiceId","","Marked void; excluded from revenue."],
    ["Payout queue","Open Payout Queue.","/admin/finance/payout/search","/admin/finance/payout/:payoutId","Pending payouts with the right hosts and amounts."],
    ["Approve a payout","Approve one.","/admin/finance/payout/:payoutId/approve","","Moves to approved; host sees it."],
    ["Reject a payout","Reject one.","/admin/finance/payout/:payoutId/reject","","Reason captured; host is told."],
    ["Initiate a payout","Initiate a transfer.","/admin/finance/payout/initiate","","NOTE: needs the 4 RazorpayX env vars. Blocked if unset — mark Blocked, not Failed."],
    ["Payout schedule","Create and view a schedule.","/admin/finance/payout/schedule/create","/admin/finance/payout/schedule/search","Saves and lists."],
    ["Reconciliation","Run reconciliation.","/admin/finance/reconciliation/run","/admin/finance/reconciliation/search","Mismatches surfaced rather than hidden."],
    ["Resolve a mismatch","Resolve one.","/admin/finance/reconciliation/:reconId/resolve","","Closed with a note."],
    ["Revenue report","Open the revenue report.","/admin/finance/reports/revenue","","Agrees with the dashboard."],
    ["Commission report","Open commission.","/admin/finance/reports/commission","","Rate applied consistently."],
    ["Tax report","Open tax.","/admin/finance/reports/tax","","GST totals match the invoices."],
    ["Cashflow","Open cashflow.","/admin/finance/reports/cashflow","","In and out over the period."],
    ["Export a report","Export any report.","/admin/finance/reports/export","","Downloads with the same numbers as the screen."],
  ]},
  { t:"Catalogue", d:"The vocabulary every listing is built from. A mistake here shows on thousands of pages.", items:[
    ["Categories","Open Categories; add one.","/admin/categories","/admin/category/create","Appears in the listing wizard and guest filters."],
    ["Category status","Turn one off.","/admin/category/update-status","","Disappears from guest-facing filters."],
    ["Delete a category","Delete a test one.","/admin/categories/delete","","Removed; listings using it are handled sensibly."],
    ["Amenities","Add and edit an amenity.","/admin/amenity/create","/admin/amenity/search","Appears in the wizard for hosts."],
    ["Amenity status","Turn one off.","/admin/amenity/update-status","","No longer offered."],
    ["Tags","Add, edit and delete a tag.","/admin/tag/create","/admin/tag/search","Appears where tags are used."],
    ["Dropdowns stay in sync","Open the listing wizard after editing.","/admin/category/list/dropdowns","/admin/amenity/list/dropdowns","New entries appear without a redeploy."],
  ]},
  { t:"Content & CMS", d:"Everything a visitor reads. Check on the live site after each save.", items:[
    ["Homepage CMS","Change hero copy and featured stays.","/admin/cms/homepage/update","/admin/cms/homepage/get","Live home page changes."],
    ["Homepage image","Replace and delete a homepage image.","/admin/cms/homepage/delete/image","","Updates; deletion doesn't break the layout."],
    ["Featured pickers","Use the property and testimonial pickers.","/admin/cms/homepage/property/dropdown","/admin/cms/homepage/testimonial/dropdown","Choices appear on the home page."],
    ["Sections","Add a CMS section.","/admin/cms/section/add","/admin/cms/section/search","Renders where intended."],
    ["Blog list","Open Blog; use the scope and state filters.","/admin/blog/listing","","Platform and Property filter correctly; Where names the property."],
    ["New platform post","Write and publish one.","/blog/create","","Appears on Explore and /blog."],
    ["New property post","Write one against a property.","/blog/create","","Appears ONLY on that stay's page, never in the main blog."],
    ["Save as draft","Save a post with only a title.","/blog/create","","Accepted. Shows as Draft, invisible publicly."],
    ["Publish a draft","Publish it from the list.","/admin/blog/status","","Goes live."],
    ["Back to draft","Send a live post back to drafts.","/admin/blog/status","","Hidden publicly and reopened for editing."],
    ["Hide a post","Toggle a published post to Hidden.","/admin/blog/status","","Off the site but still Published, not Draft."],
    ["Delete a post","Delete one.","/admin/blog/delete","","Gone from the site."],
    ["FAQs","Add, edit, delete an FAQ.","/admin/faq/add","/admin/faq/listing","Appears on the public FAQ page."],
    ["FAQ page CMS","Edit the FAQ page copy.","/admin/cms/faq-page/update","/admin/cms/FaqPage/get","Live page changes."],
    ["Terms & conditions","Edit terms.","/admin/terms-condition/add","/admin/cms/tc-page/update","Live page changes."],
    ["Contact messages","Open the inbox; read and delete.","/admin/contact/messages","/admin/contact/delete","Messages from the public form arrive here."],
  ]},
  { t:"Marketing", d:"Coupons, boosts and referrals — the levers that cost money.", items:[
    ["Coupon list","Open Coupons.","/admin/coupon/search","/admin/coupon/detail","All coupons with usage counts."],
    ["Create a coupon","Add a percentage and a flat coupon.","/admin/coupon/add","","Both apply correctly at guest checkout."],
    ["Coupon limits","Set a usage limit of 1 and redeem twice.","/admin/coupon/status/update","","Second attempt refused."],
    ["Delete a coupon","Delete a test coupon.","/admin/coupon/delete","","No longer redeemable."],
    ["Boost list","Open Boost & Promotions.","/admin/boost/list","","Active boosts with hosts and expiry."],
    ["Referrals","Open Refer.","/admin/referrals/list","","Referrals and credits, with anything suspicious visible."],
  ]},
  { t:"Reviews & moderation", d:"What guests say in public, and the ability to intervene.", items:[
    ["Review list","Open Reviews & Ratings.","/admin/property/review/search","","All reviews with property and guest."],
    ["Review detail","Open one.","/admin/property/review/detail","","Full text and rating."],
    ["Moderate","Hide or restore a review.","/admin/property/review/update","","Change reflects on the public page and the average."],
  ]},
  { t:"Operations", d:"Notifications, audit trail and platform settings.", items:[
    ["Notifications","Open notifications; mark one read.","/admin/notifications/search","/admin/notifications/:id/read","Unread count drops."],
    ["Activity log","Open Logs.","/admin/logs/list","","Admin actions recorded with who and when."],
    ["Settings","Open Settings; change something.","","","Saves and takes effect."],
    ["Test email","Send a test email.","/admin/mail/test","","Arrives. If it doesn't, mark Failed — email underpins bookings and KYC."],
  ]},
  { t:"Regression — today's fixes", d:"Shipped today. If any fails, tell me before continuing.", items:[
    ["No database errors","Force failures across the panel: bad input, double submit, offline.","","","Plain English only — never SQL, column or table names."],
    ["Typing holds focus","Type in the add-property wizard and every admin form.","","","No focus loss between characters."],
    ["Errors mark the field","Trigger a validation failure in the wizard.","","","The offending field turns red and scrolls into view."],
    ["Host search auto-selects","In Add Property, type a host's exact name and press Search.","","","Selects them and opens the wizard. No dropdown needed."],
    ["State change keeps a dropdown","Pick a state and city, then change the state.","","","City clears but stays a dropdown of the new state's cities."],
    ["Map search works","Open the map, type a place, press Enter.","/public/geocode/search","","Pin drops. An unmapped building pins the nearest sector and says so."],
    ["Edit = Add","Press Edit on any listing.","","","Same five-step wizard, everything populated, photos visible."],
    ["Admin never asked to verify","Add a property for an unverified host.","/listing/submit","","No identity demand. Listing saves and is held off the site."],
    ["Held listing emails the host","Check that host's inbox.","","","Told what was added and how to verify."],
    ["Verification releases it","Approve that host's KYC.","/admin/host/kyc/approve","","The held listing goes live on its own."],
  ]},
];
