const DATA = [
  { t:"Account & access", d:"Getting into a host account at all — the first thing that has to work.", items:[
    ["Host signup","Create a brand-new host account from the public site.","/host/register","/user/signup","TWO steps now, not three. Account is created and you're asked to verify."],
    ["No ID asked at signup","Look at step 2 of signup.","","","Address, City and Referral only. The ID type, ID number and Upload ID fields are GONE — identity is done once, by the check."],
    ["Address and City required","Leave either blank and press Create My Account.","/user/signup","","Refused, and THAT box turns red and takes focus. City no longer says (optional)."],
    ["See your password","Press the eye in any password box — signup, login, reset, change password.","","","Reveals what you typed; press again to hide. All eleven boxes on the site have it."],
    ["Email OTP on signup","The code arrives, and entering it activates the account.","/user/otp-again","/user/verify-otp","Wrong code is refused; correct code signs you in."],
    ["Host login","Sign in with the Host tab selected.","/user/login","","Lands on the host dashboard, not the guest one."],
    ["Login with your MOBILE number","Sign in using the 10-digit number instead of the email.","/user/login","","Signs you in. This failed for every number that had ever had a second account on it."],
    ["Wrong password","Sign in with a deliberately wrong password.","/user/login","","Says the password is wrong — not \"no record found\", and no database text."],
    ["Wrong tab","Sign in with a GUEST account on the Host tab.","/user/login","","Says it's a guest account and to switch tabs. It used to say \"No record found\"."],
    ["Number nobody has","Sign in with a made-up mobile number.","/user/login","","Says no account was found with that number."],
    ["Google sign-in","Use Continue with Google.","/user/auth/google","","Signs in and lands in the right portal."],
    ["Forgot password","Full reset: request, code, new password, sign in with it.","/user/forget-password","/user/forget/verify-otp","New password works; old one is refused."],
    ["Switch guest ↔ host","Swap modes from the account menu.","/switch-mode","","Both portals reachable without signing out."],
    ["Logout","Sign out, then press Back.","/user/logout","","Session is gone; protected pages don't render stale data."],
    ["Admin login page with a host signed in","Stay signed in as host, open /admin/login in the same browser.","","","The form sits still and takes typing. It used to reload itself every second until the host session was destroyed."],
    ["Admin sign-in leaves the host alone","Sign into the admin panel, then refresh a host-portal tab.","/admin/login","","The host tab is still the host portal. It used to turn into the admin panel."],
    ["Host sign-in leaves the admin alone","With the admin panel open in one tab, sign in as host in another.","/user/login","","The admin panel still works after a refresh. It used to be logged out."],
  ]},
  { t:"Identity verification", d:"The DIDIT check that gates publishing. This is where the stuck-'pending' bug lived.", items:[
    ["Start verification","From Settings, begin identity verification.","/verify/create-session","","DIDIT opens with a QR to finish on your phone."],
    ["Finish on phone","Complete ID + selfie on the phone, then return to the desktop tab.","/verify/check-session/:id","","Desktop notices on its own and flips to verified."],
    ["Status is remembered","Reload Settings after verifying.","/verify/my-session","/user/detail","Reads \"Identity verified\" — NOT \"Verification in review\"."],
    ["Not asked twice","Open Settings again the next day, and start a booking.","/verify/create-session","","A verified host is never re-asked. This was the reported bug."],
    ["Abandoned attempt","Start a verification and close it without finishing.","/verify/my-session","","You stay verified. An unfinished attempt must not revoke a good one."],
    ["Unverified cannot publish","With an unverified host, try to submit a listing.","/listing/submit","","Refused with a clear reason and a way to verify."],
    ["Told BEFORE you're blocked","Sign in as an unverified host and look at the dashboard.","/user/detail","","A prompt sits at the top offering to verify. You should learn this on arrival, not on pressing Publish."],
    ["Prompt goes away","Verify, then reload the dashboard.","","","The prompt is gone. A verified host never sees it."],
    ["Declined reads differently","On a declined account, check the dashboard prompt.","","","Says the check was declined and to try again — not \"verify your identity\" as though nothing happened."],
  ]},
  { t:"Listing a property", d:"The five-step wizard — the longest and most bug-prone flow in the product.", items:[
    ["Form loads","Open Add Property.","/listing/schema","","All five steps render; no blank sections."],
    ["Continue starts at the top","Fill a step, scroll to the bottom, press Continue.","","","The next step opens at ITS top. It used to stay scrolled where you were, so the new step's heading and first fields were above the fold."],
    ["Typing holds focus","Type a full sentence into Property name and other fields.","","","Focus never jumps. You should never have to click between letters."],
    ["Required markers","Check every mandatory field.","","","Each shows an asterisk, including Property name."],
    ["Name validation","Enter a 2-character name, then one with symbols.","/listing/step1","","Refused, and THAT field turns red and scrolls into view."],
    ["Category rules","Pick each category and check accommodation types.","/listing/step1","","Impossible combinations (PG as entire property) are not offered."],
    ["Manager authorisation","Choose Property Manager and answer No to authorisation.","/listing/step1","","Blocked from continuing, with the reason."],
    ["Capacity rule","Set maximum adults higher than total guests.","/listing/step1","","Refused with the adults/total message."],
    ["State → city","Pick a state, pick a city, then change the state.","/public/locations/cities","","City clears but stays a DROPDOWN of the new state's cities."],
    ["Map search","Open the map, type a town, press Enter.","/public/geocode/search","","Map flies there and drops a pin."],
    ["Map fallback","Search your exact society or building name.","/public/geocode/search","","If unmapped, it pins the nearest sector and says so."],
    ["My location","Press My location.","","","Either pins you, or explains (permission / accuracy). Never silent."],
    ["Step 2 details","Fill built-up area, year, and the type-specific questions.","/listing/step2","","Saves and advances; values survive going Back."],
    ["Built-up Area says its unit","Read the hint under Built-up Area.","/listing/schema","","Tells you to enter just the number and pick the unit in Area Unit beside it, with a worked example."],
    ["Step 3 amenities","Tick amenities, experiences, views, house rules.","/listing/step3","","All groups save."],
    ["Step 4 pricing","Set nightly price, minimum (floor) and ideal price.","/listing/step4","","Saves. The floor is never shown to guests anywhere."],
    ["Money fields carry examples","Read under nightly price, discounts, cleaning fee and deposit.","","","Each gives a typical range. Once a nightly rate is entered the hints do the arithmetic against it."],
    ["Auto-reject / auto-accept say their unit","Open Advanced limits under Negotiation.","","","Both labels read \"(₹ per night)\" and say in words that they are amounts, not percentages, with the sum worked out."],
    ["Damage policy shows what to write","Look at the two damage boxes.","","","Each has a worked example in the box and a line saying what to cover."],
    ["Step 5 identity — verified host","As a DIDIT-verified host, open step 5.","/listing/readiness/:id","","Identity verification shows a green confirmation and NO fields. You are not asked for your ID a third time."],
    ["Step 5 identity — unverified host","As an unverified host, open step 5.","","","Offers the face-and-document check first, with the manual fields underneath as the fallback."],
    ["Aadhaar accepts digits only","Choose Aadhaar, then try typing letters.","","","Letters are refused as you type; hint says 12 digits."],
    ["Bank details are not re-asked","With a payout account set up, open step 5.","/listing/readiness/:id","","Shows the account already on file with a Change link. No retyping. \"Use a different account for this property\" opens the fields if you want them."],
    ["Bank name refuses digits","Type 4974000100062410 into Bank name.","","","Nothing is accepted. It takes letters only."],
    ["Readiness counts what you've done","With identity verified and payouts set up, read the readiness panel.","/listing/readiness/:id","","Identity verified and Bank details are BOTH ticked. They used to stay unticked and cost 20 points."],
    ["Upload a PDF document","Upload a PDF as your identity or ownership document.","/listing/media/upload","","Accepted. Every PDF was rejected before — the route ran an image-only filter."],
    ["PDF is refused as a photo","Try uploading a PDF into the listing photos.","/listing/media/upload","","Refused, in plain English, saying PDFs are for verification documents."],
    ["Photo upload","Upload several photos; delete one; set a cover.","/listing/media/upload","/listing/media/:id","All appear, deletion sticks, cover is honoured."],
    ["Readiness score","Watch the readiness panel on step 5.","/listing/readiness/:id","","Score reflects what you've actually filled in."],
    ["Submit","Accept declarations and submit.","/listing/submit","","Confirms, and the listing shows as submitted."],
    ["Resume a draft","Leave halfway, come back later.","/listing/draft/:id","","Reopens where you left off with everything intact."],
    ["Edit an existing property","Open a live listing from Properties and edit it.","/listing/draft/:id","","Opens the SAME five-step form, every field and photo populated."],
  ]},
  { t:"Property management", d:"Everything a host does to a listing once it exists.", items:[
    ["Properties list","Open My Properties.","/host/property-search","","All listings, correct status, correct photos."],
    ["Take offline / put live","Toggle a listing inactive, then active.","/host/property/update-status","","Disappears from public search when off; returns when on."],
    ["Change cover photo","Set a different cover.","/host/update-property-cover","","Changes on the card and the detail page."],
    ["Cancellation policy","Set a policy; check the pending-policy prompt.","/host/properties/cancellation-policy","/host/properties/policy-pending","Saves and shows on the public page."],
    ["Delete a property","Delete a test listing.","/host/delete-property","","Asks first; disappears from search afterwards."],
  ]},
  { t:"Calendar & availability", d:"The dates a host can and can't be booked on.", items:[
    ["View calendar","Open the calendar for a property.","/host/calendar","","Existing bookings show as taken."],
    ["Block dates","Block a range.","/host/calendar/block","","Marked blocked immediately."],
    ["Unblock","Release that range.","/host/calendar/unblock","","Bookable again."],
    ["Blocked dates really block","As a guest, try to book blocked dates.","/booking/property-availability","","Greyed out in the guest date picker."],
  ]},
  { t:"Negotiations", d:"The heart of the product. Test as host AND guest — use two browsers.", items:[
    ["Offer arrives","As a guest, offer BELOW the floor.","/host/negotiations/list","/user/negotiations/offer","Appears in the host's Negotiations with dates and amount."],
    ["Live update","Keep Negotiations open while the guest offers.","","","Appears without a refresh."],
    ["Accept","Accept the offer.","/host/negotiations/respond","","Marked accepted; guest sees the deal and a coupon."],
    ["Counter","Counter with a different price.","/host/negotiations/respond","","Guest sees the counter and can accept it."],
    ["Decline","Decline an offer.","/host/negotiations/respond","","Marked declined; guest is told."],
    ["Auto-accept","As a guest, offer AT or ABOVE the floor.","","","Accepted instantly with no host action. Host is told, not asked."],
    ["Offer expiry","Leave an offer untouched for 30+ minutes.","","","Expires; guest is told the host was unavailable."],
    ["Agreed price is charged","Guest completes checkout after a deal.","/booking/create","","Charged the negotiated price, never the list price."],
    ["Floor never leaks","Check the guest-side property page and offer dialog.","","","Your minimum price appears nowhere."],
  ]},
  { t:"Bookings", d:"From a confirmed booking to the guest arriving and leaving.", items:[
    ["Bookings list","Open Bookings.","/host/bookings/search","","Filters by status; totals look right."],
    ["Booking detail","Expand a booking.","/host/bookings/detail/:id","","Guest, dates, nights, amount, payment state."],
    ["Staying guest & ID","Open a booking made FOR someone else.","/guest-profiles/for-booking/:id","","Shows the traveller; View ID opens their document."],
    ["Confirm a booking","Confirm a pending booking.","/host/confirm-book","","Status changes; guest is notified."],
    ["Check-in","Mark a guest checked in.","/host/booking/check-in","","Recorded against the booking."],
    ["No-show","Mark a no-show.","/host/booking/no-show","","Recorded; refund rules apply correctly."],
    ["Cancel","Cancel a booking as host.","/host/cancel-booking","","Reason captured; refund follows the policy."],
    ["History","Open past bookings.","/host/booking-history","","Completed and cancelled stays listed."],
  ]},
  { t:"Money", d:"Earnings, payouts and paperwork. Check the arithmetic, not just that pages load.", items:[
    ["Dashboard","Open the host dashboard.","/host/dashboard/summary","","Tiles match reality — no placeholder numbers."],
    ["Earnings","Open Earnings.","/host/earnings/summary","","Totals reconcile with your bookings."],
    ["Payout account","Add or change bank details.","/host/payout-account/update","/host/payout-account/get","Saves; account number is masked when shown back."],
    ["Payout history","Open payout history.","/host/payout/history","","Past payouts with dates and amounts."],
    ["Statements","Open and download a statement.","/host/statements/search","/host/statements/download/:id","File downloads and opens."],
    ["Invoice","Download an invoice for a paid booking.","/host/invoice/:payId/download","","PDF has correct amounts and GST."],
    ["Transactions","Open transaction history.","/host/transaction-history","","Every movement accounted for."],
  ]},
  { t:"Growth", d:"The optional tools hosts use to get more bookings.", items:[
    ["Boost catalogue","Open Boost & Promotions.","/host/boost/list","","Plans and prices render."],
    ["Buy a boost","Order and pay for a boost.","/host/boost/order","/host/boost/verify","Payment completes and activates."],
    ["Boost is visible","Check the boosted listing in guest search.","/host/boost/activate","","Marked sponsored and ranks higher."],
    ["Refer & earn","Open Refer, copy the code, redeem on a new account.","/user/referrals/summary","","Credit lands after the referred booking."],
    ["Performance","Open Performance.","/host/performance/summary","","Views, conversion and rating look plausible."],
    ["Reviews","Check reviews on your listing.","/user/reviews/list","","Guest reviews appear; ratings average correctly."],
  ]},
  { t:"Messages & support", d:"How a host talks to guests and to Aajoo.", items:[
    ["Guest messages","Open a thread and reply.","/user/messages/threads","","Message sends; guest receives it."],
    ["Notifications","Open notifications; mark one read.","/host/notifications/search","/host/notifications/:id/read","Unread count decreases."],
    ["Raise a ticket","Create a support ticket.","/host/support/tickets/create","","Ticket appears with a reference."],
    ["Reply to a ticket","Reply on an open ticket.","/host/support/tickets/reply","/host/support/tickets/search","Thread updates."],
  ]},
  { t:"Profile & account", d:"The host's own details, and the security around changing them.", items:[
    ["View profile","Open Profile.","/host/profile/get","","Your details, correct."],
    ["Edit profile","Change name and address.","/host/profile/update","","Saves and persists after reload."],
    ["Profile photo","Upload and remove a photo.","/user/add/profile-pic","/user/delete/profile-pic","Updates everywhere it appears."],
    ["Change password","Change it, then sign in with the new one.","/user/update-password","","Old password refused afterwards."],
    ["Change phone","Change your mobile number.","/user/security/otp","","Requires an emailed code first."],
    ["Email is read-only","Try to change your email.","","","Not editable — by design."],
    ["Delete account","Only on a throwaway account.","/user/delete","","Asks for confirmation; access ends."],
  ]},
  { t:"Host feedback document", d:"The twelve items from your host problems write-up. Each was fixed on web AND in the app.", items:[
    ["1 — Password eye","Every password box on the site and in the app.","","","Reveal toggle present."],
    ["2 — Address and City required","Signup step 2.","","","Both marked *, both enforced, the offending box highlighted."],
    ["3 — Login errors say what's wrong","Wrong password / wrong tab / unknown number.","","","Three different, true messages. No \"No record found\"."],
    ["4 — Login with mobile","A 10-digit number plus password.","","","Signs in. Was the duplicate-account bug."],
    ["5 — Unverified prompt","Host and guest dashboards, web and app.","","","A prompt at the top, on arrival."],
    ["6 — Continue scrolls to top","Every step of the wizard.","","","Next step starts at its top."],
    ["7 — Built-up Area unit","Step 2.","","","Hint names the Area Unit field and gives a range."],
    ["8 — Auto-reject / auto-accept units","Step 4, Advanced limits.","","","Labels say ₹ per night; hints work the sum out."],
    ["9 — Pricing examples","Step 4.","","","Ranges on every money field."],
    ["10 — Damage examples","Step 4, Damage policy.","","","Worked examples in both boxes."],
    ["11 — Identity not re-asked, upload works, selfie opens camera","Step 5.","","","Verified hosts see a confirmation. PDFs upload. Live selfie asks for the front camera, falling back to the file picker."],
    ["12 — Bank name refuses digits","Step 5 and host profile.","","","Letters only, both places."],
    ["De-duplication — ID","Signup, DIDIT, wizard step 5.","","","Asked ONCE, by DIDIT. Signup no longer asks; the wizard confirms instead."],
    ["De-duplication — bank","Host profile vs wizard step 5.","","","Asked once per host, not once per property."],
  ]},
  { t:"Regression — earlier fixes", d:"The specific things fixed earlier. If any of these fail, tell me immediately.", items:[
    ["No database errors","Force failures: bad input, submit twice, go offline mid-save.","","","You NEVER see SQL, column or table names. Plain English only."],
    ["Errors mark the field","Trigger any validation failure.","","","The offending field turns red and scrolls into view."],
    ["Form doesn't save per keystroke","Open the network tab and type in the wizard.","","","No requests fire while typing. Saving happens on Continue."],
    ["Admin lists for a host","As ADMIN, add a property for an UNVERIFIED host.","/listing/submit","","Admin is never asked to verify. Listing saves."],
    ["Held until verified","Check that listing on the public site.","","","Not visible. Host gets an email explaining how to verify."],
    ["Goes live on verification","Have that host complete verification.","/verify/create-session","","The listing turns on by itself."],
  ]},
];
const LEGACY_KEYS={"0|0": "Account & access::Host signup", "0|1": "Account & access::Email OTP on signup", "0|2": "Account & access::Host login", "0|3": "Account & access::Wrong password", "0|4": "Account & access::Google sign-in", "0|5": "Account & access::Forgot password", "0|6": "Account & access::Switch guest ↔ host", "0|7": "Account & access::Logout", "1|0": "Identity verification::Start verification", "1|1": "Identity verification::Finish on phone", "1|2": "Identity verification::Status is remembered", "1|3": "Identity verification::Not asked twice", "1|4": "Identity verification::Abandoned attempt", "1|5": "Identity verification::Unverified cannot publish", "2|0": "Listing a property::Form loads", "2|1": "Listing a property::Typing holds focus", "2|2": "Listing a property::Required markers", "2|3": "Listing a property::Name validation", "2|4": "Listing a property::Category rules", "2|5": "Listing a property::Manager authorisation", "2|6": "Listing a property::Capacity rule", "2|7": "Listing a property::State → city", "2|8": "Listing a property::Map search", "2|9": "Listing a property::Map fallback", "2|10": "Listing a property::My location", "2|11": "Listing a property::Step 2 details", "2|12": "Listing a property::Step 3 amenities", "2|13": "Listing a property::Step 4 pricing", "2|15": "Listing a property::Aadhaar accepts digits only", "2|16": "Listing a property::Photo upload", "2|17": "Listing a property::Readiness score", "2|18": "Listing a property::Submit", "2|19": "Listing a property::Resume a draft", "2|20": "Listing a property::Edit an existing property", "3|0": "Property management::Properties list", "3|1": "Property management::Take offline / put live", "3|2": "Property management::Change cover photo", "3|3": "Property management::Cancellation policy", "3|4": "Property management::Delete a property", "4|0": "Calendar & availability::View calendar", "4|1": "Calendar & availability::Block dates", "4|2": "Calendar & availability::Unblock", "4|3": "Calendar & availability::Blocked dates really block", "5|0": "Negotiations::Offer arrives", "5|1": "Negotiations::Live update", "5|2": "Negotiations::Accept", "5|3": "Negotiations::Counter", "5|4": "Negotiations::Decline", "5|5": "Negotiations::Auto-accept", "5|6": "Negotiations::Offer expiry", "5|7": "Negotiations::Agreed price is charged", "5|8": "Negotiations::Floor never leaks", "6|0": "Bookings::Bookings list", "6|1": "Bookings::Booking detail", "6|2": "Bookings::Staying guest & ID", "6|3": "Bookings::Confirm a booking", "6|4": "Bookings::Check-in", "6|5": "Bookings::No-show", "6|6": "Bookings::Cancel", "6|7": "Bookings::History", "7|0": "Money::Dashboard", "7|1": "Money::Earnings", "7|2": "Money::Payout account", "7|3": "Money::Payout history", "7|4": "Money::Statements", "7|5": "Money::Invoice", "7|6": "Money::Transactions", "8|0": "Growth::Boost catalogue", "8|1": "Growth::Buy a boost", "8|2": "Growth::Boost is visible", "8|3": "Growth::Refer & earn", "8|4": "Growth::Performance", "8|5": "Growth::Reviews", "9|0": "Messages & support::Guest messages", "9|1": "Messages & support::Notifications", "9|2": "Messages & support::Raise a ticket", "9|3": "Messages & support::Reply to a ticket", "10|0": "Profile & account::View profile", "10|1": "Profile & account::Edit profile", "10|2": "Profile & account::Profile photo", "10|3": "Profile & account::Change password", "10|4": "Profile & account::Change phone", "10|5": "Profile & account::Email is read-only", "10|6": "Profile & account::Delete account", "11|0": "Regression — earlier fixes::No database errors", "11|1": "Regression — earlier fixes::Errors mark the field", "11|2": "Regression — earlier fixes::Form doesn't save per keystroke", "11|3": "Regression — earlier fixes::Admin lists for a host", "11|4": "Regression — earlier fixes::Held until verified", "11|5": "Regression — earlier fixes::Goes live on verification"};
