const DATA = [
  { t:"Finding a stay", d:"Everything before a guest cares who you are — search has to work signed out.", items:[
    ["Home loads","Open the site signed out.","/homepage/content","","Hero, categories and every rail render. No empty sections."],
    ["Search by place","Type a destination in the header search and go.","/properties/search","","Results are near that place, not the whole country."],
    ["Dates narrow results","Add check-in and check-out.","/booking/property-availability","","Stays already booked for those nights disappear."],
    ["Guest count filters","Set 6 guests.","/properties/search","","Only stays that sleep 6 remain."],
    ["Category rails","Open Villas, Cottages, Farm Stays from Find Your Perfect Stay.","/common/categories","","Each shows stays of that type."],
    ["Property Type filter is honest","Tick Homestays in the filter rail and read the badge on EVERY card.","","","Every card says Homestays. A villa named \"Chomu HomeStay\" used to pass this filter on the strength of its name and show up wearing a Villas badge."],
    ["Dates really remove stays","Search an area, note a stay, then search the same area for nights that stay is already booked on.","/properties/search","","It is gone from the results. It used to sit there and refuse only at checkout."],
    ["Checkout day is still bookable","Search for nights starting on the DAY a booking ends.","","","The stay is available. A booking occupies nights, not the checkout day — losing that day would cost a night on every booking."],
    ["Map on search","Switch to the map view and click a pin.","","","Pin opens the right stay."],
    ["LUXE mode","Turn LUXE on.","/properties/search","","Only luxury-marked stays; the whole page restyles."],
    ["Pre-booking","Open Pre-Booking.","/pre-booking","","Upcoming/advance stays list correctly."],
    ["Empty search","Search somewhere with nothing listed.","","","Says so helpfully — not a blank screen or a spinner forever."],
  ]},
  { t:"The property page", d:"Where a guest decides. Check the facts are real, not placeholders.", items:[
    ["Gallery","Open a stay with photos; open the gallery.","/properties/detail","","All photos load; cover is first."],
    ["No photos","Open a stay without photos.","","","Branded placeholder, never a broken image."],
    ["One page, not tabs","Scroll the whole property page from top to bottom.","/properties/detail","","About, Amenities, House Rules, Location, Guest experiences, Host and Things to know are ALL on one scroller. Nothing is hidden behind a tab any more."],
    ["Section jump row","Tap a chip in the row under the header.","","","It scrolls to that section and every other section stays on the page. The highlight follows you as you scroll back by hand."],
    ["About this place","Read the About section on a stay whose host wrote a long description.","/properties/detail","","The full description is there. It used to be one line with a lot of white space under it."],
    ["Amenities","Compare against what the host ticked.","","","Only what was ticked; nothing invented."],
    ["Show all amenities","Open a stay with a long amenity list.","","","Shows the first group or two with \"Show all N amenities\" underneath. Tapping it opens the rest; Show less closes it again."],
    ["Nearby distances","Check the nearby section.","","","Absent when the host never entered them — not zeros."],
    ["Show all nearby","Same control on What's nearby.","","","Trims the same way and has its own Show all."],
    ["Staff reads as words","Find the staff line under House rules.","","","Reads Housekeeping. NOT [\"housekeeping\"] with brackets and quote marks."],
    ["House rules in two columns","Look at House rules on a wide screen.","","","Laid out in a grid, not one tall list."],
    ["Map","Check the location map.","","","Correct area; exact pin only if the host allowed it."],
    ["Reviews","Read the reviews.","/properties/reviews/list","","Real reviews; average matches."],
    ["Guides & stories","Open a stay that has posts (id 29250).","/blog/search","","Shows that stay's posts. Absent on stays without any."],
    ["Price rail","Set dates and guests.","","","Nights, taxes and total add up."],
    ["Floor never shown","Look everywhere on the page.","","","The host's minimum price appears nowhere."],
    ["Book Now follows you down","On a desktop, scroll from the top of the page to the reviews.","","","The booking card stays on screen the whole way. You should never have to scroll back to the top to book."],
    ["No search bar here","Look at the header on a property page.","","","Where / When / Who is NOT there — you are already looking at one stay. It used to sit there pushing the booking card below the fold."],
    ["Branded photo placeholder","Open a stay with no photographs.","","","The frame carries the Aajoo house mark and wordmark, not a generic broken-image icon."],
  ]},
  { t:"Weekend pricing", d:"The host sets a higher Friday/Saturday rate. Every number a guest sees has to use it — this was collected at listing time and read by nothing.", items:[
    ["Weekend nights cost more","Open the date picker on a stay with a weekend rate set.","/booking/property-availability","","Friday and Saturday show the weekend price. Every day used to show the weekday one."],
    ["Headline price follows your dates","Pick a weekend, then look at the big price at the top of the page.","","","It changes to the weekend rate. It used to stay at the weekday price and contradict the total right below it."],
    ["A mixed stay prices each night","Book a stay running from Thursday to Sunday.","","","The breakdown charges each night at its own rate and the nights add up to the total."],
    ["Price cannot be tampered with","Technical, optional: change the price in the booking request before paying.","/booking/create","","Refused. The server works the nightly rates out again and will not accept a total it did not quote."],
  ]},
  { t:"Account & access", d:"Signing up and getting back in.", items:[
    ["Signup","Create a new guest account.","/user/signup","","Created, then asked to verify."],
    ["Email OTP","Enter the emailed code.","/user/verify-otp","/user/otp-again","Wrong code refused; right one signs you in."],
    ["Login","Sign in with the Guest tab.","/user/login","","Lands on the guest dashboard."],
    ["Wrong password","Try a wrong password.","/user/login","","Says the password is wrong. No database text."],
    ["Google sign-in","Continue with Google.","/user/auth/google","","Signs in correctly."],
    ["Google sign-up asks for a number ONCE","Sign up with a brand-new Google account and type your mobile number.","/user/update","","It saves and you are in. It used to answer \"Enter the code we emailed you. Request one first if you haven't.\" under the number field, with no way forward — a new Google account could not finish signing up."],
    ["Changing the number later DOES need a code","Now go to Settings and change that number to a different one.","/user/security/otp","","This one asks for an emailed code, and the code step actually opens. Only the FIRST number is exempt."],
    ["Forgot password","Request, code, new password, sign in.","/user/forget-password","/user/forget/verify-otp","New password works; old one refused."],
    ["Logout","Sign out then press Back.","/user/logout","","No stale data on protected pages."],
  ]},
  { t:"Identity verification", d:"The check that stands between a guest and a confirmed booking.", items:[
    ["Prompted at checkout","As an unverified guest, try to book.","/verify/create-session","","Told clearly, with a way to verify from that screen."],
    ["Complete the check","Finish ID and selfie.","/verify/check-session/:id","","Returns verified without re-entering the booking."],
    ["Stays verified","Reload Settings the next day.","/verify/my-session","/user/detail","Reads Identity verified — never back to review."],
    ["Not re-asked","Book again as a verified guest.","","","No verification step at all. This was the reported bug."],
    ["Abandoned attempt","Start verification and close it.","","","You remain verified."],
  ]},
  { t:"Negotiating a price", d:"The feature the product is built around. Use a second browser as the host.", items:[
    ["Send an offer","Offer below the listed price with dates.","/user/negotiations/offer","","Confirms it went to the host, with the 30-minute window."],
    ["One dialog, not browser pop-ups","Press Make an offer and watch what opens.","","","A single styled dialog with the price AND the message in it. Never the browser's own grey prompt box, and never two of them one after the other."],
    ["My negotiations","Open Negotiations from your account menu.","/user/negotiations/list","","Every offer you have made, its status, and what the host countered with. There was no page for this at all before."],
    ["Several rounds each way","Counter the host's counter, and have them counter again.","/user/negotiations/offer","","Up to three offers from you and three from the host. It used to be one each and then a dead end."],
    ["Rounds run out","Use all three of your offers.","","","Told plainly that you have no offers left, with the option to book at the price on the table."],
    ["Above the floor","Offer at or above the host's minimum.","","","Accepted instantly, with a coupon code."],
    ["Host accepts","Have the host accept a low offer.","","","You see the deal and the percentage saved."],
    ["Host counters","Have the host counter.","","","Counter shown; you can accept it."],
    ["Host declines","Have the host decline.","","","Told plainly; can still book at list price."],
    ["Offer expires","Leave an offer unanswered 30+ minutes.","","","Told the host was unavailable."],
    ["Deal reaches checkout","Book after a deal.","/user/coupons/validate","","Discount applied automatically at the agreed rate."],
    ["Above list price","Try offering more than the listed price.","","","Refused — nothing to negotiate."],
    ["Deal expires","Wait 24 hours after a deal, then book.","","","Coupon no longer applies; full price. Correct behaviour."],
  ]},
  { t:"Booking & payment", d:"From Book Now to a confirmation. Money is involved — check every number.", items:[
    ["Review page","Press Book Now.","","","Stay, dates, nights, guests all correct."],
    ["Contact details","Check the prefilled name, phone, email.","/user/detail","","Filled from your profile, editable."],
    ["Guest picker","Change the number of guests.","","","Same control as the header search; total updates."],
    ["Dates still free","Book dates someone took while you browsed.","/booking/property-availability","","Told before payment, not after."],
    ["Approval-required stay says so","Book a stay whose host chose \"I approve each booking\".","/booking/create","","Reads Awaiting approval — NOT Confirmed — and tells you how long the host has to answer. It used to confirm instantly and ignore the host's setting."],
    ["Instant-book stay confirms","Book a stay set to instant booking.","/booking/create","","Confirms straight away. The host's approval setting should be the ONLY thing that changes this."],
    ["Host approves","Have the host approve it from their Bookings.","/host/confirm-book","","Yours flips to confirmed and you are notified."],
    ["Pay at property","Choose Reserve now, pay on arrival.","/booking/create","","Booking is created with a reference and reads Payment pending. It must NOT read Confirmed — no money has moved yet."],
    ["Pay online","Pay by card or UPI in test mode.","/create/payment-verify","","Payment completes and the booking confirms."],
    ["Wallet","Apply wallet credit.","/user/wallet","","Split shown before paying; balance drops by that much."],
    ["Coupon","Apply a coupon code.","/user/coupons/validate","","Discount matches; a bad code is refused clearly."],
    ["Failure is visible","Force a refusal (e.g. an unpaid pay-at-property booking).","","","Reason stays on the page. Not a button that does nothing."],
    ["A refused payment says WHY","Make a payment fail — a very large amount, or the failure card in test mode.","","","The message is the gateway's own reason (\"Amount exceeds maximum amount allowed\", \"card declined\"), not a bare \"Payment failed. Please try again.\""],
    ["Confirmation","Reach the confirmed screen.","/booking/confirmation","","Reference, map, directions, invoice note."],
    ["Confirmation email","Check your inbox.","","","Arrives with the right amounts."],
  ]},
  { t:"Booking for someone else", d:"New. A verified guest booking on behalf of family, a colleague or a child.", items:[
    ["Who is this for","Open the review page.","","","Asks who is staying. I'm staying is the default."],
    ["Add a traveller","Add name, phone, email, age, gender.","/guest-profiles","","Saved and selected."],
    ["Upload their ID","Attach a government ID.","/guest-profiles/document","","Shows ID on file afterwards."],
    ["Reused next time","Start another booking.","/guest-profiles","","They're already in the list — no retyping."],
    ["Booking carries them","Complete the booking.","/booking/create","","Booking is attached to that traveller."],
    ["Host can see them","As the host, open that booking.","/guest-profiles/for-booking/:id","","Sees the staying guest and can open the ID."],
    ["Remove a traveller","Delete one from the list.","/guest-profiles/delete","","Asks first, then removes."],
  ]},
  { t:"My bookings", d:"Everything after paying.", items:[
    ["Dashboard","Open your account.","/user/ongoing/bookings","","Next stay and recent activity are right."],
    ["Upcoming","Open Upcoming.","/user/booking-history","","Future stays with correct dates."],
    ["Ongoing","During a stay, open Ongoing.","","","Current stay with host contact."],
    ["Next booking","Open Next Booking.","","","The soonest stay, with directions."],
    ["Directions","Press Get directions.","","","Opens maps at the right place."],
    ["Past stays","Open Past Stays.","","","Completed stays, with a prompt to review."],
    ["Cancel — see the refund first","Start a cancellation.","/user/cancel/quote","","Refund amount shown BEFORE you confirm."],
    ["Cancel","Confirm it.","/user/cancel/booking","","Cancelled; host notified; refund matches the quote."],
    ["Cancelled list","Open Cancelled.","/account/cancelled","","Shows there with the refund state."],
    ["Host cancels — you are told why","Have the host cancel one of your bookings with a reason.","/host/cancel-booking","","An email arrives naming the stay, the refund, and \"Reason given:\" with the host's own words. The host cannot cancel without giving one."],
    ["Invoice","Download an invoice.","/user/invoice/:bookId/download","","Opens with correct amounts and GST."],
  ]},
  { t:"After the stay", d:"Reviews and the things guests come back for.", items:[
    ["Write a review","Review a completed stay.","/user/review-add","","Saves; appears on the property."],
    ["Edit a review","Change it.","","","Text stays put while you type — this was broken in the app."],
    ["My reviews","Open your reviews.","/user/reviews/list","","All of them listed."],
    ["Saved stays","Save and unsave from a card and a detail page.","/user/saved-properties","","Both stay in sync."],
    ["Refer & earn","Copy your code; redeem on a new account.","/user/referrals/summary","","Credit lands after the referred booking."],
    ["Transactions","Open Transactions.","/user/history","","Every payment and refund accounted for."],
  ]},
  { t:"Messages & support", d:"Reaching a host, or reaching Aajoo.", items:[
    ["Message a host","Open a thread and send.","/user/messages/threads","","Host receives it."],
    ["Notifications","Open notifications; mark one read.","/user/notification/Listing","/user/notification/mark-read","Unread count drops."],
    ["Support","Open Support and submit a question.","/contact/message","","Confirms it was sent."],
    ["Chatbot","Open the chat widget.","/bp/session/start","","Recognises you and answers about your booking."],
  ]},
  { t:"Profile & settings", d:"The guest's own details and the security around them.", items:[
    ["Profile","Open and edit your profile.","/user/detail","","Saves and persists."],
    ["Profile photo","Upload and remove.","/user/add/profile-pic","/user/delete/profile-pic","Updates everywhere."],
    ["Change password","Change it, then sign in again.","/user/update-password","","Old one refused."],
    ["Change phone","Change your mobile.","/user/security/otp","","Requires an emailed code first."],
    ["Email read-only","Try to change your email.","","","Not editable, by design."],
    ["Delete account","On a throwaway account only.","/user/delete","","Confirms first; access ends."],
  ]},
  { t:"Content pages", d:"The pages that sell the platform. Check for placeholder text.", items:[
    ["Blog index","Open the blog.","/blog/search","","Real posts, not \"blog one\"."],
    ["Blog post","Open one.","/blog/:id","","Full article; More from the blog rails on a phone."],
    ["Explore blog rail","Scroll the home page.","","","From the blog scrolls sideways, six posts."],
    ["About","Open About.","","","Illustrations on every Values and Different card."],
    ["FAQ","Open FAQ; open one question by its own link.","/public/faqs","/public/faqs/feedback","Answers expand; the was-this-helpful vote records."],
    ["Contact","Send a contact message.","/contact/message","","Confirms; admin receives it."],
    ["Newsletter","Subscribe from the footer.","/newsletter/subscribe","","Confirms; a bad email is refused."],
    ["Help centre & policies","Open Help Centre, Terms, Privacy.","","","Real content, no lorem, no overflow on a phone."],
    ["Search bar only where it belongs","Visit About, the blog, FAQ, Contact, a property page, and the booking review.","","","NONE of them shows Where / When / Who. Only Explore, Search and Pre-Booking do — the pages that actually browse stays."],
    ["Pre-Booking has ONE search bar","Open Pre-Booking and count the search bars.","","","One, in the header. The old Destination / Check-in / Check-out form underneath is gone, and the dates you pick still ride into every stay you open from the page."],
  ]},
  { t:"On a phone", d:"Most guests are on a phone. Test at 390–412px wide.", items:[
    ["Search sheet","Open search on a phone.","","","Full-screen sheet; X closes it; nothing overflows."],
    ["Cards two-up","Check the home and search grids.","","","Two across, not one tall column."],
    ["Rails scroll","Swipe the stay and blog rails.","","","Scroll sideways smoothly."],
    ["Sticky Book Now","Scroll a property page.","","","Book bar follows; doesn't cover content."],
    ["Nothing overflows","Scroll every page top to bottom.","","","No horizontal scrollbar anywhere."],
  ]},
  { t:"Regression — this week's fixes", d:"Shipped 22–23 August across web and the Android app. If any of these fails, tell me before continuing.", items:[
    ["Status never contradicts itself","Compare ONE booking on your dashboard, in My Bookings, and on the host's screen.","","","All of them say the same thing. One screen reading Confirmed while another still offers a Confirm button is the bug."],
    ["Traveller ID upload","Upload an ID for someone you are booking for.","/guest-profiles/:id/document","","It uploads. It used to fail with 'unable to upload the ID' every single time."],
    ["App property page matches","Open the same stay in the Android app.","","","The same stacked sections in the same order, with the same Show all controls. Not a tab switcher."],
    ["No database errors","Force failures anywhere.","","","Plain English only — never SQL, columns or table names."],
    ["Old property links","Open /property/detail/29250 directly.","","","Redirects to the new page with negotiation intact."],
    ["Payment errors persist","Trigger a refused booking.","","","Reason stays on screen with a way forward."],
    ["Property posts hide","Open a stay with no posts (29251).","","","No empty Guides & stories heading."],
  ]},
  { t:"Regression — 24 Aug guest fixes", d:"From the guest-errors document. Use property 29262 (Malhotra Villa) for anything about price or guest count — it is the one test listing with weekend rates and a capacity set. If any of these fails, tell me before continuing.", items:[
    ["Your dates follow you","Search with dates and guests, then open any stay from the results.","","","The property page already has your dates and your guest count. You are not asked twice."],
    ["…and follow you to checkout","From that stay, press Book Now.","","","The review page carries the same dates and the same party size."],
    ["A deal carries its dates","Open My Negotiations on an accepted offer and press Book at the agreed price.","/negotiations/mine","","The stay opens with the nights the deal was struck over — not an empty listing."],
    ["Verifying does not lose your booking","Start a booking, get sent to ID verification, finish it.","/verify/check-session/:id","","You come back to the SAME booking, still holding your property, dates and guests."],
    ["Your own held dates stay yours","Start a booking, abandon it at payment, then book the same dates again.","/booking/add","","It goes through. It used to refuse with ‘these dates are already booked’ — against your own unpaid hold."],
    ["The calendar is not cut off","Open the check-in field on a property page.","","","The whole calendar is visible, including the ‹ previous-month arrow. Page back a month and it responds."],
    ["The guest stepper is not cut off","Open the Guests field on a property page.","","","Adults, Children and Infants all show in full, with a line naming the limit."],
    ["Guest count stops at capacity","On 29262, hold the + on Adults.","","","It stops at 8 and says so. It does not keep counting up."],
    ["Weekend nights cost more","On 29262, pick Fri 28 → Mon 31 Aug.","","","₹19,000 for 3 nights — ₹6,000 Friday, ₹6,500 Saturday, ₹6,500 Sunday — and the headline reads ₹6,333 avg / night, not ₹5,000."],
    ["LUXE dresses only LUXE stays","Turn LUXE on, then open an ordinary listing.","","","The gold skin steps aside for that listing and returns when you leave it."],
    ["The map stays under the header","Scroll the search results with the map beside them.","","","The map and its ‘N stays on map’ badge stay below the header. The logo and nav are never covered."],
    ["View Details opens THAT booking","From Upcoming, and again from Past stays, press View Details.","","","Each opens the booking you pressed it on. No hop to Ongoing or to Next Booking."],
    ["A wrong password says so, where you are","Sign in with a bad password without scrolling.","/user/login","","The message finds you. You do not have to scroll up to discover it."],
    ["Blog search finds an id","Search the blog by a post’s id, and again by a phrase from its body.","/blog/search","","Both find the post. Only the title used to match."],
    ["Guest count changes the price","On 29262, take the party from 8 to 10 with Fri 28 → Mon 31 Aug.","","","A line appears: 2 extra guests × ₹1,000 × 3 nights = ₹6,000. Total goes ₹19,950 → ₹26,250. It used to ignore the guest count entirely."],
    ["The stepper reaches the chargeable extras","On 29262, hold + on Adults.","","","It stops at 10 — capacity 8 plus the 2 extra the host will take — not at 8."],
    ["That price survives to checkout","Book that 10-guest stay and read the review page, then the payment page.","/booking/add","","The same ₹26,250, with the extra-guest line still named. It is not refused as ‘the price for these dates has changed’."],
    ["Changing the party at checkout re-prices","On the review page, change 10 guests to 8.","","","The extra-guest line disappears and the total falls back to ₹19,950."],
    ["The app charges the same","Open 29262 in the Android app, set 10 guests, same dates.","","","Same ₹26,250, and the booking stores the guest count. The app never used to ask, or send it."],
    ["Another tab signing in is announced","Sign in as a guest in one tab, then sign in as a host in a second. Return to the first.","","","The first tab says ‘You signed in somewhere else’ with a Reload button — it does not silently become the host."],
  ]},
];
