const DATA = [
  { t:"Finding a stay", d:"Everything before a guest cares who you are — search has to work signed out.", items:[
    ["Home loads","Open the site signed out.","/homepage/content","","Hero, categories and every rail render. No empty sections."],
    ["Search by place","Type a destination in the header search and go.","/properties/search","","Results are near that place, not the whole country."],
    ["Dates narrow results","Add check-in and check-out.","/booking/property-availability","","Stays already booked for those nights disappear."],
    ["Guest count filters","Set 6 guests.","/properties/search","","Only stays that sleep 6 remain."],
    ["Category rails","Open Villas, Cottages, Farm Stays from Find Your Perfect Stay.","/common/categories","","Each shows stays of that type."],
    ["Map on search","Switch to the map view and click a pin.","","","Pin opens the right stay."],
    ["LUXE mode","Turn LUXE on.","/properties/search","","Only luxury-marked stays; the whole page restyles."],
    ["Pre-booking","Open Pre-Booking.","/pre-booking","","Upcoming/advance stays list correctly."],
    ["Empty search","Search somewhere with nothing listed.","","","Says so helpfully — not a blank screen or a spinner forever."],
  ]},
  { t:"The property page", d:"Where a guest decides. Check the facts are real, not placeholders.", items:[
    ["Gallery","Open a stay with photos; open the gallery.","/properties/detail","","All photos load; cover is first."],
    ["No photos","Open a stay without photos.","","","Branded placeholder, never a broken image."],
    ["Tabs","Click About, Amenities, House Rules, Location, Host, Policies.","","","Each scrolls to real content the host entered."],
    ["Amenities","Compare against what the host ticked.","","","Only what was ticked; nothing invented."],
    ["Nearby distances","Check the nearby section.","","","Absent when the host never entered them — not zeros."],
    ["Map","Check the location map.","","","Correct area; exact pin only if the host allowed it."],
    ["Reviews","Read the reviews.","/properties/reviews/list","","Real reviews; average matches."],
    ["Guides & stories","Open a stay that has posts (id 29250).","/blog/search","","Shows that stay's posts. Absent on stays without any."],
    ["Price rail","Set dates and guests.","","","Nights, taxes and total add up."],
    ["Floor never shown","Look everywhere on the page.","","","The host's minimum price appears nowhere."],
  ]},
  { t:"Account & access", d:"Signing up and getting back in.", items:[
    ["Signup","Create a new guest account.","/user/signup","","Created, then asked to verify."],
    ["Email OTP","Enter the emailed code.","/user/verify-otp","/user/otp-again","Wrong code refused; right one signs you in."],
    ["Login","Sign in with the Guest tab.","/user/login","","Lands on the guest dashboard."],
    ["Wrong password","Try a wrong password.","/user/login","","Says the password is wrong. No database text."],
    ["Google sign-in","Continue with Google.","/user/auth/google","","Signs in correctly."],
    ["Forgot password","Request, code, new password, sign in.","/user/forget-password","/user/forget/verify-otp","New password works; old one refused."],
    ["Logout","Sign out then press Back.","/user/logout","","No stale data on protected pages."],
  ]},
  { t:"Identity verification", d:"The check that stands between a guest and a confirmed booking.", items:[
    ["Prompted at checkout","As an unverified guest, try to book.","/verify/create-session","","Told clearly, with a way to verify from that screen."],
    ["Complete the check","Finish ID and selfie.","/verify/check-session/:id","","Returns verified without re-entering the booking."],
    ["Stays verified","Reload Settings the next day.","/verify/my-session","/user/detail","Reads Identity verified — never back to review."],
    ["Not re-asked","Book again as a verified guest.","","","No verification step at all. This was the reported bug."],
    ["Abandoned attempt","Start verification and close it.","","","You remain verified."],
  ]},
  { t:"Negotiating a price", d:"The feature the product is built around. Use a second browser as the host.", items:[
    ["Send an offer","Offer below the listed price with dates.","/user/negotiations/offer","","Confirms it went to the host, with the 30-minute window."],
    ["Above the floor","Offer at or above the host's minimum.","","","Accepted instantly, with a coupon code."],
    ["Host accepts","Have the host accept a low offer.","","","You see the deal and the percentage saved."],
    ["Host counters","Have the host counter.","","","Counter shown; you can accept it."],
    ["Host declines","Have the host decline.","","","Told plainly; can still book at list price."],
    ["Offer expires","Leave an offer unanswered 30+ minutes.","","","Told the host was unavailable."],
    ["Deal reaches checkout","Book after a deal.","/user/coupons/validate","","Discount applied automatically at the agreed rate."],
    ["Above list price","Try offering more than the listed price.","","","Refused — nothing to negotiate."],
    ["Deal expires","Wait 24 hours after a deal, then book.","","","Coupon no longer applies; full price. Correct behaviour."],
  ]},
  { t:"Booking & payment", d:"From Book Now to a confirmation. Money is involved — check every number.", items:[
    ["Review page","Press Book Now.","","","Stay, dates, nights, guests all correct."],
    ["Contact details","Check the prefilled name, phone, email.","/user/detail","","Filled from your profile, editable."],
    ["Guest picker","Change the number of guests.","","","Same control as the header search; total updates."],
    ["Dates still free","Book dates someone took while you browsed.","/booking/property-availability","","Told before payment, not after."],
    ["Pay at property","Choose Reserve now, pay on arrival.","/booking/create","","Booking confirms with a reference."],
    ["Pay online","Pay by card or UPI in test mode.","/create/payment-verify","","Payment completes and the booking confirms."],
    ["Wallet","Apply wallet credit.","/user/wallet","","Split shown before paying; balance drops by that much."],
    ["Coupon","Apply a coupon code.","/user/coupons/validate","","Discount matches; a bad code is refused clearly."],
    ["Failure is visible","Force a refusal (e.g. an unpaid pay-at-property booking).","","","Reason stays on the page. Not a button that does nothing."],
    ["Confirmation","Reach the confirmed screen.","/booking/confirmation","","Reference, map, directions, invoice note."],
    ["Confirmation email","Check your inbox.","","","Arrives with the right amounts."],
  ]},
  { t:"Booking for someone else", d:"New. A verified guest booking on behalf of family, a colleague or a child.", items:[
    ["Who is this for","Open the review page.","","","Asks who is staying. I'm staying is the default."],
    ["Add a traveller","Add name, phone, email, age, gender.","/guest-profiles","","Saved and selected."],
    ["Upload their ID","Attach a government ID.","/guest-profiles/document","","Shows ID on file afterwards."],
    ["Reused next time","Start another booking.","/guest-profiles","","They're already in the list — no retyping."],
    ["Booking carries them","Complete the booking.","/booking/create","","Booking is attached to that traveller."],
    ["Host can see them","As the host, open that booking.","/guest-profiles/for-booking/:id","","Sees the staying guest and can open the ID."],
    ["Remove a traveller","Delete one from the list.","/guest-profiles/delete","","Asks first, then removes."],
  ]},
  { t:"My bookings", d:"Everything after paying.", items:[
    ["Dashboard","Open your account.","/user/ongoing/bookings","","Next stay and recent activity are right."],
    ["Upcoming","Open Upcoming.","/user/booking-history","","Future stays with correct dates."],
    ["Ongoing","During a stay, open Ongoing.","","","Current stay with host contact."],
    ["Next booking","Open Next Booking.","","","The soonest stay, with directions."],
    ["Directions","Press Get directions.","","","Opens maps at the right place."],
    ["Past stays","Open Past Stays.","","","Completed stays, with a prompt to review."],
    ["Cancel — see the refund first","Start a cancellation.","/user/cancel/quote","","Refund amount shown BEFORE you confirm."],
    ["Cancel","Confirm it.","/user/cancel/booking","","Cancelled; host notified; refund matches the quote."],
    ["Cancelled list","Open Cancelled.","/account/cancelled","","Shows there with the refund state."],
    ["Invoice","Download an invoice.","/user/invoice/:bookId/download","","Opens with correct amounts and GST."],
  ]},
  { t:"After the stay", d:"Reviews and the things guests come back for.", items:[
    ["Write a review","Review a completed stay.","/user/review-add","","Saves; appears on the property."],
    ["Edit a review","Change it.","","","Text stays put while you type — this was broken in the app."],
    ["My reviews","Open your reviews.","/user/reviews/list","","All of them listed."],
    ["Saved stays","Save and unsave from a card and a detail page.","/user/saved-properties","","Both stay in sync."],
    ["Refer & earn","Copy your code; redeem on a new account.","/user/referrals/summary","","Credit lands after the referred booking."],
    ["Transactions","Open Transactions.","/user/history","","Every payment and refund accounted for."],
  ]},
  { t:"Messages & support", d:"Reaching a host, or reaching Aajoo.", items:[
    ["Message a host","Open a thread and send.","/user/messages/threads","","Host receives it."],
    ["Notifications","Open notifications; mark one read.","/user/notification/Listing","/user/notification/mark-read","Unread count drops."],
    ["Support","Open Support and submit a question.","/contact/message","","Confirms it was sent."],
    ["Chatbot","Open the chat widget.","/bp/session/start","","Recognises you and answers about your booking."],
  ]},
  { t:"Profile & settings", d:"The guest's own details and the security around them.", items:[
    ["Profile","Open and edit your profile.","/user/detail","","Saves and persists."],
    ["Profile photo","Upload and remove.","/user/add/profile-pic","/user/delete/profile-pic","Updates everywhere."],
    ["Change password","Change it, then sign in again.","/user/update-password","","Old one refused."],
    ["Change phone","Change your mobile.","/user/security/otp","","Requires an emailed code first."],
    ["Email read-only","Try to change your email.","","","Not editable, by design."],
    ["Delete account","On a throwaway account only.","/user/delete","","Confirms first; access ends."],
  ]},
  { t:"Content pages", d:"The pages that sell the platform. Check for placeholder text.", items:[
    ["Blog index","Open the blog.","/blog/search","","Real posts, not \"blog one\"."],
    ["Blog post","Open one.","/blog/:id","","Full article; More from the blog rails on a phone."],
    ["Explore blog rail","Scroll the home page.","","","From the blog scrolls sideways, six posts."],
    ["About","Open About.","","","Illustrations on every Values and Different card."],
    ["FAQ","Open FAQ; open one question by its own link.","/public/faqs","/public/faqs/feedback","Answers expand; the was-this-helpful vote records."],
    ["Contact","Send a contact message.","/contact/message","","Confirms; admin receives it."],
    ["Newsletter","Subscribe from the footer.","/newsletter/subscribe","","Confirms; a bad email is refused."],
    ["Help centre & policies","Open Help Centre, Terms, Privacy.","","","Real content, no lorem, no overflow on a phone."],
  ]},
  { t:"On a phone", d:"Most guests are on a phone. Test at 390–412px wide.", items:[
    ["Search sheet","Open search on a phone.","","","Full-screen sheet; X closes it; nothing overflows."],
    ["Cards two-up","Check the home and search grids.","","","Two across, not one tall column."],
    ["Rails scroll","Swipe the stay and blog rails.","","","Scroll sideways smoothly."],
    ["Sticky Book Now","Scroll a property page.","","","Book bar follows; doesn't cover content."],
    ["Nothing overflows","Scroll every page top to bottom.","","","No horizontal scrollbar anywhere."],
  ]},
  { t:"Regression — today's fixes", d:"Shipped today. If any fails, tell me before continuing.", items:[
    ["No database errors","Force failures anywhere.","","","Plain English only — never SQL, columns or table names."],
    ["Old property links","Open /property/detail/29250 directly.","","","Redirects to the new page with negotiation intact."],
    ["Payment errors persist","Trigger a refused booking.","","","Reason stays on screen with a way forward."],
    ["Property posts hide","Open a stay with no posts (29251).","","","No empty Guides & stories heading."],
  ]},
];
const LEGACY_KEYS={"0|0": "Finding a stay::Home loads", "0|1": "Finding a stay::Search by place", "0|2": "Finding a stay::Dates narrow results", "0|3": "Finding a stay::Guest count filters", "0|4": "Finding a stay::Category rails", "0|5": "Finding a stay::Map on search", "0|6": "Finding a stay::LUXE mode", "0|7": "Finding a stay::Pre-booking", "0|8": "Finding a stay::Empty search", "1|0": "The property page::Gallery", "1|1": "The property page::No photos", "1|2": "The property page::Tabs", "1|3": "The property page::Amenities", "1|4": "The property page::Nearby distances", "1|5": "The property page::Map", "1|6": "The property page::Reviews", "1|7": "The property page::Guides & stories", "1|8": "The property page::Price rail", "1|9": "The property page::Floor never shown", "2|0": "Account & access::Signup", "2|1": "Account & access::Email OTP", "2|2": "Account & access::Login", "2|3": "Account & access::Wrong password", "2|4": "Account & access::Google sign-in", "2|5": "Account & access::Forgot password", "2|6": "Account & access::Logout", "3|0": "Identity verification::Prompted at checkout", "3|1": "Identity verification::Complete the check", "3|2": "Identity verification::Stays verified", "3|3": "Identity verification::Not re-asked", "3|4": "Identity verification::Abandoned attempt", "4|0": "Negotiating a price::Send an offer", "4|1": "Negotiating a price::Above the floor", "4|2": "Negotiating a price::Host accepts", "4|3": "Negotiating a price::Host counters", "4|4": "Negotiating a price::Host declines", "4|5": "Negotiating a price::Offer expires", "4|6": "Negotiating a price::Deal reaches checkout", "4|7": "Negotiating a price::Above list price", "4|8": "Negotiating a price::Deal expires", "5|0": "Booking & payment::Review page", "5|1": "Booking & payment::Contact details", "5|2": "Booking & payment::Guest picker", "5|3": "Booking & payment::Dates still free", "5|4": "Booking & payment::Pay at property", "5|5": "Booking & payment::Pay online", "5|6": "Booking & payment::Wallet", "5|7": "Booking & payment::Coupon", "5|8": "Booking & payment::Failure is visible", "5|9": "Booking & payment::Confirmation", "5|10": "Booking & payment::Confirmation email", "6|0": "Booking for someone else::Who is this for", "6|1": "Booking for someone else::Add a traveller", "6|2": "Booking for someone else::Upload their ID", "6|3": "Booking for someone else::Reused next time", "6|4": "Booking for someone else::Booking carries them", "6|5": "Booking for someone else::Host can see them", "6|6": "Booking for someone else::Remove a traveller", "7|0": "My bookings::Dashboard", "7|1": "My bookings::Upcoming", "7|2": "My bookings::Ongoing", "7|3": "My bookings::Next booking", "7|4": "My bookings::Directions", "7|5": "My bookings::Past stays", "7|6": "My bookings::Cancel — see the refund first", "7|7": "My bookings::Cancel", "7|8": "My bookings::Cancelled list", "7|9": "My bookings::Invoice", "8|0": "After the stay::Write a review", "8|1": "After the stay::Edit a review", "8|2": "After the stay::My reviews", "8|3": "After the stay::Saved stays", "8|4": "After the stay::Refer & earn", "8|5": "After the stay::Transactions", "9|0": "Messages & support::Message a host", "9|1": "Messages & support::Notifications", "9|2": "Messages & support::Support", "9|3": "Messages & support::Chatbot", "10|0": "Profile & settings::Profile", "10|1": "Profile & settings::Profile photo", "10|2": "Profile & settings::Change password", "10|3": "Profile & settings::Change phone", "10|4": "Profile & settings::Email read-only", "10|5": "Profile & settings::Delete account", "11|0": "Content pages::Blog index", "11|1": "Content pages::Blog post", "11|2": "Content pages::Explore blog rail", "11|3": "Content pages::About", "11|4": "Content pages::FAQ", "11|5": "Content pages::Contact", "11|6": "Content pages::Newsletter", "11|7": "Content pages::Help centre & policies", "12|0": "On a phone::Search sheet", "12|1": "On a phone::Cards two-up", "12|2": "On a phone::Rails scroll", "12|3": "On a phone::Sticky Book Now", "12|4": "On a phone::Nothing overflows", "13|0": "Regression — today's fixes::No database errors", "13|1": "Regression — today's fixes::Old property links", "13|2": "Regression — today's fixes::Payment errors persist", "13|3": "Regression — today's fixes::Property posts hide"};
